name: Pull Request
description: Please fill out the following fields, they will help us to process your pull request faster.
title: "[Type]: Brief description"
body:
    - type: markdown
      attributes:
          value: "## Description\nPlease provide a detailed description of your pull request."
    - type: input
      id: changes
      attributes:
          label: What changes have you made?
          description: Describe the modifications you've made.
          placeholder: e.g., Fixed a bug in...
      validations:
          required: true
    - type: checkboxes
      id: type-of-change
      attributes:
          label: Type of change
          description: What type of change does your pull request introduce?
          options:
              - label: Bug fix (non-breaking change which fixes an issue)
                required: true
              - label: New feature (non-breaking change which adds functionality)
                required: true
              - label: Documentation update
                required: true
    - type: textarea
      id: testing
      attributes:
          label: How has this been tested?
          description: Please describe the tests that were used to verify your changes.
          placeholder: Include any specific details about your testing methodology.
      validations:
          required: true
footer: Thank you for contributing!
