[target.x86_64-unknown-linux-gnu]
pre-build = "rustembedded/cross:x86_64-unknown-linux-gnu-0.2.1"

[target.arm-unknown-linux-gnueabihf]
pre-build = "rustembedded/cross:arm-unknown-linux-gnueabihf-0.2.1"

[target.aarch64-unknown-linux-gnu]
pre-build = "rustembedded/cross:aarch64-unknown-linux-gnu-0.2.1"
