name: Feature Request
description: Suggest a new feature or enhancement
# labels: NOT YET DECIDED
body:
    - type: markdown
      attributes:
          value: |
              Thank you for suggesting a new feature. Please describe your idea and how it would benefit users.

    - type: checkboxes
      id: ensure-no-duplicates
      attributes:
          value: |
              Before submitting this issue, please check if someone else has already suggested the same feature.
      validations:
          required: true

    - type: textarea
      id: feature-description
      attributes:
          label: Feature Description
          description: A clear and concise description of what you want to happen.
      validations:
          required: true

    - type: textarea
      id: benefit
      attributes:
          label: Benefit
          description: Explain how this feature would benefit users.
      validations:
          required: true

    - type: markdown
      attributes:
          value: |
              By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Nodura/Contower/blob/stable/CONTRIBUTING.md#code-of-conduct).
