name: Mark and Close Stale Issues

on:
    schedule:
        - cron: "0 0 * * *" # Runs at midnight every day
    workflow_dispatch:

jobs:
    stale:
        runs-on: ubuntu-latest
        permissions:
            issues: write
            pull-requests: write
        steps:
            - name: Mark and close stale issues and PRs
              uses: actions/stale@v9
              with:
                  days-before-stale: 30
                  days-before-close: 7
                  stale-issue-label: "LS-Stale"
                  stale-pr-label: "LS-Stale"
                  stale-issue-message: "This issue has been marked as stale because it has been inactive for 30 days. Please update the issue to remove the stale label."
                  stale-pr-message: "This PR has been marked as stale because it has been inactive for 30 days. Please update the PR to remove the stale label."
                  close-issue-message: "This issue has been closed due to inactivity."
                  close-pr-message: "This PR has been closed due to inactivity."
                  exempt-issue-labels: "P-Prevent-stale"
                  exempt-pr-labels: "P-Prevent-stale"
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
